### ISSUE TITLE
Crash when adding leg

### ISSUE THREAD

**Issue by kirbix12** [TheEveEye/SCR-Realism-Project#15]
Line 35 of Time.cs returned with another Exception Unhandled error reading "System.FormatException: 'String '1.14:00:15' was not recognized as a valid DateTime.'"

Driver command was executed successfully before this

**Comment by TheEveEye** [comment]
Could you provide the command that you entered?

**Comment by kirbix12** [comment]
add leg 0 1 4560 sc sac

**Comment by TheEveEye** [comment]
Thank you.

**Comment by kirbix12** [comment]
Found an exception: When 0 was entered into the add leg command, it took the leg

**Comment by TheEveEye** [comment]
So you entered `0` into the Starting Frame Parameter? That helps out a ton thanks.

**Comment by kirbix12** [comment]
Another exception found: Route 1 cannot be over 1121 starting frames
