### ISSUE TITLE
Exception Thrown Error when attempting to cancel to delete a leg

### ISSUE THREAD

**Issue by kirbix12** [TheEveEye/SCR-Realism-Project#36]
Line 680 of Program.cs returned with an Exception Thrown error with: 
```
System.NullReferenceException: 'Object reference not set to an instance of an object.'

selectedLeg was null.
```
while attempting to cancel to delete a leg via. "delete leg" command.

Command line also spat out: 
```
Are you sure that you want to remove leg 0?
```
after it "successfully" execute the attempted cancelation. It does not matter if a leg was added

**Comment by TheEveEye** [comment]
Works with the newest commit on branch #17
