### ISSUE TITLE
Running remove leg command with an invalid leg crash program

### ISSUE THREAD

**Issue by kirbix12** [TheEveEye/SCR-Realism-Project#43]
Line 683 of Leg.cs returned with an Exception Unhandled error with the following exception:
```
System.ArgumentOutOfRangeException: 'Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')'
```
when entering command ```remove leg``` and then entering an invalid leg (can be also entered with no given leg to remove)

**Comment by kirbix12** [comment]
Reopened the issue still relating to this bug: The issue is on line 690 with an Exception Thrown error with the following:
```
System.NullReferenceException: 'Object reference not set to an instance of an object.'

selectedLeg was null.
```
It is located on the same .cs file. Even after Pull Request #45, the console now returns with an invalid argument and wanting to delete Leg 0, but still crashes.

**Comment by TheEveEye** [comment]
It should work now

**Comment by kirbix12** [comment]
Closed under Build 90
